#!/bin/bash

###
###  resync: lazy way to resync sources
###

## set necessary permanent values
# directories
declare -r ROOT="${HOME}/bin/romtools"
declare -r LOGS="${ROOT}logs"
# files
declare -r DIRS="${ROOT}/resync.dirs"
declare -r CMDS="${ROOT}/resync.post"
declare -r OPTS="${ROOT}/resync.opts"

# set colors to be used for output
declare -r red='\033[0;31m'
declare -r redbold='\033[01;31m'
declare -r green='\033[0;32m'
declare -r greenbold='\033[01;32m'
declare -r blue='\033[0;34m'
declare -r bluebold='\033[01;34m'
declare -r magenta='\033[0;35m'
declare -r magentabold='\033[01;35m'
declare -r cyan='\033[0;36m'
declare -r cyanbold='\033[01;36m'
declare -r clear='\033[0m'

# etc stuff
declare sourceopts='yes'
declare dopost='yes'

fatal() {
  printf "\n${redbold}Fatal error: ${red}%s\n ${clear}" "$*"
  exit 1
}

usage() {
cat <<EOF
resync: automate syncing custom rom sources
Usage: $0 [options]

-h    show this usage text
-s    skip running repo sync
-o    skip syncing rom source optimizations
-d    skip resyncing deleted directories

version: 1.2
EOF

exit 0
}

args() {
  while getopts ":sod" opts; do
    case "${opts}" in
      "s")
        # skip to post
        printf "${bluebold}>> ${blue}Argument '-s' given, skipping sync\n${clear}"
        post && exit 0
        ;;
    
      "o")
        # let the script know to not apply source optimizations
        printf "${bluebold}>> ${blue}Argument '-o' given, skipping source optimization\n${clear}"
	declare sourceopts="no"
        ;;

      "d")
        # do not reclone deleted directories
        printf "${bluebold}>> ${blue}Argument '-d' given, skipping post-sync\n${clear}"
	declare dopost="no"
        ;;

      *)
        usage
        ;;
    esac
  done

  firstrun "$@"
  return
}

firstrun() {
  # let the output of 'repo sync' tell us what to delete
  printf "${cyanbold}>> ${cyan}First run of 'repo sync' to determine directories that need to be recloned\n${clear}"
  if repo sync -j"$(nproc --all)" --no-tags --no-clone-bundle --current-branch --force-sync &> "$DIRS" ; then
    printf "${magenta}The first run of repo sync was successful. Skipping to applying source patches...\n${clear}"
    exit 0
  fi
  
  # remove the cruft and keep only the list of dirs that need to be removed
  sed -i '1,/Failing repos/d' "$DIRS"
  sed -i '$d' "$DIRS"

  rmdirs "$@"
  return
}

rmdirs() {
  local -a _dirs
  readarray -t _dirs < "${DIRS}"

  # test if each dir exists, then "rm -rf" every item in dirs array
  for _dir in "${_dirs[@]}"; do
    printf "${greenbold}>> ${green}Removing directory '${_dir}'${clear}\n"
    if [[ -d "${_dir}" ]]; then
      if rm -rf "${_dir}"; then
        printf "${cyanbold}>> ${cyan}Removed directory '${_dir}'${clear}\n"
      else
        fatal "Failed to remove directory '${_dir}'"
      fi
    else
      fatal "Directory '${_dir}' does not exist!"
    fi
  done

  sync "$@"
  return
}

sync() {
  # run the "real" sync command
  printf "${bluebold}>> ${blue}Syncing sources\n${clear}"
  if ! repo sync -j$(nproc --all) --no-tags --no-clone-bundle --current-branch --force-sync ; then
    fatal 'Failed to sync'
  fi

  post "$@"
  return
}

post() {
  case "$dopost" in
    "yes"|"y")
      # source cmds file
      printf "${greenbold}>> ${green}Resyncing deleted directories\n${clear}"
      if ! source "${CMDS}" $@; then
        fatal "Failed to source ' (${CMDS})"
      fi

      case "$sourceopts" in
        "yes"|"y")
          printf "${magentabold}>> ${magenta}Applying source optimizations\n${clear}"
          if ! source "${OPTS}" $@; then
            fatal "Failed to source ' (${OPTS})"
          fi
          printf "${magentabold}>> ${magenta}Done.\n${clear}"
          ;;

        "no"|"n")
          # do nothing, don't source the opts
          printf "${bluebold}>> ${blue}Skipping source optimizations.\n${clear}"
          ;;

        *)
          fatal "Unable to tell if I should run source optimizations!"
          ;;
        esac
      ;;
    "no"|"n")
      # do not resync deleted dirs
     true
     ;;
  esac

  mods "$@"
  return
}

mods() {
  printf "${cyanbold}>> ${cyan}Applying source patches\n${clear}"

  # source any file in DIRS ending in .mod
  for f in $(ls "${ROOT}" | grep '.mod'); do
    printf "${magenta}Applying source patch '$f'...${clear}"
      if ! source "${ROOT}/${f}"; then
        fatal "Failed to source ' (${f})"
      fi
    printf "${cyan} Done.${clear}\n"
  done 

  return
}

main() {
  # make needed files if they don't exist
  if ! test -d "${ROOT}"; then
    mkdir -p "${ROOT}"
  fi
  for i in ${DIRS} ${CMDS} ${OPTS}; do
    if ! test -f "$i"; then
      touch "$i"
    fi
  done

  # get the script running
  args "$@"

  # script has been ran
  printf "\n${greenbold}>> ${green}Resync has finished successfully.\n${clear}"
}

main "$@"
